[general]
import = [
    "$HOME/.config/alacritty/themes/monokai_pro.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = ["-1"]

[window]
dynamic_padding = false

[font]
normal = { family = "Cica", style = "Regular" }
bold = { family = "Cica", style = "Bold" }
italic = { family = "Cica", style = "Italic" }
bold_italic = { family = "Cica", style = "BoldItalic" }
size = 13.0
