# Prefix key from Ctrl-b to Ctrl-q
set -g prefix C-q
unbind C-b

# Reduce delay
set -sg escape-time 0

# Enable True Color (24bit color)
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# enable mouse operation
set -g mouse on

# vertical -> -, horizontal -> |
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# inherit current directory when opening new window
bind c new-window -c "#{pane_current_path}"

# Enable Vim key-bind
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# use vim key-bind during copy-mode
setw -g mode-keys vi

# start selection with 'v' and yank with 'y'
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xsel -bi"
